#!/usr/bin/env bash
# Publish a file to the kotha-audio host.
#
#   ./publish.sh greeting.mp3
#   ./publish.sh flow-b.xml ~/Desktop/clips/hold.mp3
#   ./publish.sh --force play.xml      # overwrite a live file without asking
#   ./publish.sh                       # publish whatever is already sitting here
#
# Copies each file to the repo root, commits, pushes to main, refreshes the URL
# table in README.md, and prints the public URL for everything it published.
#
# Two behaviours worth knowing:
#   * .mp3 files get a byte-identical .mpga twin. Pages serves .mp3 as
#     "audio/mp3", which Twilio's <Play> does not document as supported;
#     .mpga is served as "audio/mpeg", which it does. Use the .mpga URL.
#   * Overwriting a file that is already live prompts first, because a Twilio
#     call may be pointing at it. Pass --force to skip the prompt.

set -euo pipefail

cd "$(dirname "$0")"

force=0
args=()
for a in "$@"; do
  case "$a" in
    --force|-f) force=1 ;;
    *) args+=("$a") ;;
  esac
done

# Public base URL, derived from the git remote rather than hardcoded.
remote="$(git remote get-url origin)"
slug="${remote#*github.com}"; slug="${slug#[:/]}"; slug="${slug%.git}"
user="$(echo "${slug%%/*}" | tr '[:upper:]' '[:lower:]')"
repo="${slug##*/}"
base="https://${user}.github.io/${repo}"

shopt -s nullglob

content_type() {
  case "${1##*.}" in
    mpga|mp2|m2a) echo "audio/mpeg" ;;
    mp3)          echo "audio/mp3" ;;
    wav)          echo "audio/wav" ;;
    xml)          echo "application/xml" ;;
    *)            echo "-" ;;
  esac
}

# ---- 1. copy incoming files in -------------------------------------------
published=()
for src in "${args[@]:-}"; do
  [[ -z "$src" ]] && continue
  if [[ ! -f "$src" ]]; then
    echo "skipping: no such file: $src" >&2
    continue
  fi
  name="$(basename "$src")"
  if [[ "$(cd "$(dirname "$src")" && pwd -P)" != "$(pwd -P)" ]]; then
    if [[ -f "./$name" && $force -eq 0 ]] && ! cmp -s "$src" "./$name"; then
      echo
      echo "WARNING: $name already exists here and is already published."
      echo "A Twilio call may be pointing at ${base}/${name}"
      if [[ -t 0 ]]; then
        read -r -p "Overwrite it? [y/N] " reply
        [[ "$reply" =~ ^[Yy]$ ]] || { echo "skipped: $name"; continue; }
      else
        echo "skipped: $name (re-run with --force to overwrite)"; continue
      fi
    fi
    cp -- "$src" "./$name"
    echo "copied in: $name"
  fi
  published+=("$name")
done

# ---- 2. keep .mpga twins in sync -----------------------------------------
for f in *.mp3; do
  twin="${f%.mp3}.mpga"
  if [[ ! -f "$twin" || "$f" -nt "$twin" ]]; then
    cp -- "$f" "$twin"; echo "twinned:   $twin"
  fi
done
for twin in *.mpga; do
  [[ -f "${twin%.mpga}.mp3" ]] || { rm -- "$twin"; echo "removed orphan: $twin"; }
done

# ---- 3. sanity-check any XML ---------------------------------------------
for x in *.xml; do
  first="$(head -c 1 "$x")"
  [[ "$first" == "<" ]] || echo "WARNING: $x does not start with '<' - is it valid XML?" >&2
done

# ---- 4. regenerate the README URL table ----------------------------------
tmp="$(mktemp)"
{
  echo "<!-- URLS:START - generated by publish.sh, do not edit by hand -->"
  echo
  echo "| File | Public URL | Content-Type |"
  echo "| --- | --- | --- |"
  for f in *.mpga *.mp3 *.wav *.xml; do
    printf '| `%s` | %s/%s | `%s` |\n' "$f" "$base" "$f" "$(content_type "$f")"
  done
  echo
  echo "<!-- URLS:END -->"
} > "$tmp"

awk -v tf="$tmp" '
  /<!-- URLS:START/ { system("cat " tf); skip=1; next }
  /<!-- URLS:END/   { skip=0; next }
  !skip             { print }
' README.md > README.new && mv README.new README.md
rm -f "$tmp"

# ---- 5. commit and push ---------------------------------------------------
git add -A
if git diff --cached --quiet; then
  echo "Nothing to publish - already up to date."
else
  if [[ ${#published[@]} -gt 0 ]]; then
    git commit -q -m "Publish: ${published[*]}"
  else
    git commit -q -m "Update published assets"
  fi
  git push -q origin main
  echo "Pushed. Pages usually goes live within a minute."
fi

# ---- 6. print URLs --------------------------------------------------------
echo
if [[ ${#published[@]} -gt 0 ]]; then
  echo "Public URL(s):"
  for name in "${published[@]}"; do
    if [[ "$name" == *.mp3 ]]; then
      echo "  ${base}/${name%.mp3}.mpga   <- use this in TwiML (audio/mpeg)"
      echo "  ${base}/${name}   (audio/mp3, for browsers)"
    else
      echo "  ${base}/${name}   ($(content_type "$name"))"
    fi
  done
else
  echo "Everything currently live:"
  for f in *.mpga *.xml; do echo "  ${base}/${f}"; done
fi
